CREATE DATABASE IF NOT EXISTS loginbd;

USE loginbd;

CREATE TABLE users(
    id INT NOT NULL PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
);